on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@beta-v4
      with:
        server: ftp.samkirkland.com
        username: voxel-github-publish@voxel.samkirkland.com
        password: ${{ secrets.ftp_password }}
